document.addEventListener('DOMContentLoaded',async()=>{
  const session=await OBA_CREW_AUTH.requireCrewSession();if(!session)return;
  OBA_CREW_SHELL.mount({page:'adventures'});OBA_CREW_SHELL.renderCrewIdentity(session);
  const $=id=>document.getElementById(id),esc=OBA_CREW_CORE.esc,api=OBA_CREW_CORE.api;
  const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
  const f=$('detailsForm'),recap=$('recapForm'),update=$('updateForm');let current=null,all=[],detail=null,can={};
  const allowed={draft:['upcoming','cancelled'],upcoming:['event_day','live','postponed','rescheduled','cancelled'],event_day:['live','postponed','cancelled'],live:['recap_pending','ended_early'],ended_early:['recap_pending'],recap_pending:['past'],postponed:['upcoming','rescheduled','cancelled'],rescheduled:['upcoming','cancelled'],past:[],cancelled:[]};
  const label=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
  const date=s=>s?new Date(s).toLocaleString('en-US',{timeZone:'America/Los_Angeles',dateStyle:'medium',timeStyle:'short'}):'—';
  const local=s=>{if(!s)return '';const d=new Date(s),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);const v=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${v.year}-${v.month}-${v.day}T${v.hour}:${v.minute}`};
  const localISO=s=>s?new Date(s).toISOString():'';
  const banner=(id,message,kind='success')=>{const e=$(id);e.hidden=!message;e.className='adv-alert '+kind;e.textContent=message||''};
  const notify=(message,kind='success')=>banner('message',message,kind);
  const setFields=(form,record,keys)=>keys.forEach(k=>{const e=form.elements.namedItem(k);if(e)e.type==='checkbox'?e.checked=!!record[k]:e.value=record[k]??''});
  const fieldData=(form,keys)=>Object.fromEntries(keys.map(k=>[k,form.elements.namedItem(k)?.value??'']));
  const fields=['title','slug','event_type','summary','description','timezone'];
  const fmtHistory=(items)=>items.map(h=>`<article class="adv-history"><strong>${esc(label(h.action||h.new_status))}</strong><small>${esc(date(h.created_at))} · ${esc(h.actor_type||'crew')} ${esc(h.actor_id||'')}</small>${h.reason?`<p>${esc(h.reason)}</p>`:''}<details><summary>Technical details</summary><pre>${esc(JSON.stringify(h,null,2))}</pre></details></article>`).join('')||'<p class="adv-muted">No history yet.</p>';
  function tab(name){notify('');document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.adv-section').forEach(x=>x.classList.toggle('active',x.dataset.section===name));}
  $('tabs').onclick=e=>{const b=e.target.closest('button[data-tab]');if(b)tab(b.dataset.tab)};
  function formPayload(){return {...fieldData(f,fields),starts_at:localISO($('startAt').value),ends_at:localISO($('endAt').value),location_name:$('locationName').value,location_address:$('locationAddress').value,adventure_id:current?.adventure_id||null}}
  async function list(){try{const d=await api('/crew/adventures?q='+encodeURIComponent($('search').value)+'&status='+encodeURIComponent($('filter').value));all=d.adventures||[];can=d.access||{};$('newAdventure').hidden=!can.create;const count=s=>all.filter(x=>x.lifecycle_status===s).length;$('stats').innerHTML=[['All',all.length],['Upcoming',count('upcoming')],['Live',count('live')],['Recap Pending',count('recap_pending')]].map(([k,v])=>`<div class="adv-stat"><strong>${v}</strong>${k}</div>`).join('');$('rows').innerHTML=all.map(a=>`<tr data-id="${esc(a.adventure_id)}"><td><strong>${esc(a.title)}</strong><br><small>${esc(a.slug)}</small></td><td>${esc(label(a.event_type))}</td><td>${esc(date(a.starts_at))}</td><td>${esc(a.location_name||'TBD')}</td><td><span class="adv-pill">${esc(label(a.lifecycle_status))}</span></td><td>${esc(label(a.recap_status))}</td></tr>`).join('')||'<tr><td colspan="6">No Adventures found.</td></tr>';banner('listMessage','')}catch(e){banner('listMessage',e.message,'error')}}
  $('rows').onclick=e=>{const row=e.target.closest('tr[data-id]');if(row)open(row.dataset.id)};
  async function open(id){try{detail=id?await api('/crew/adventures/detail?id='+encodeURIComponent(id)):null;current=detail?.adventure||null;const a=current||{title:'',slug:'',event_type:'oba_popup',timezone:'America/Los_Angeles',starts_at:'',ends_at:''};setFields(f,a,fields);$('startAt').value=local(a.starts_at);$('endAt').value=local(a.ends_at);$('locationName').value=a.location_name||'';$('locationAddress').value=a.location_address||'';setFields(recap,a,['recap_status','recap_title','recap_body','crowd_report']);$('formTitle').textContent=a.title||'New Adventure';$('formMeta').textContent=current?`${a.adventure_id} · ${label(a.lifecycle_status)}`:'Draft · Not yet saved';const access=detail?.access||{edit:can.create};$('overview').innerHTML=current?`<p><strong>${esc(a.title)}</strong> · ${esc(label(a.event_type))}</p><p>${esc(a.summary||'No summary yet.')}</p><p><strong>When:</strong> ${esc(date(a.starts_at))} – ${esc(date(a.ends_at))}</p><p><strong>Where:</strong> ${esc(a.location_name||'Not set')}</p><p><strong>Lifecycle:</strong> ${esc(label(a.lifecycle_status))}</p><p><strong>Recap:</strong> ${esc(label(a.recap_status))}</p>`:'<p>Complete the Details, Schedule and Location tabs to create an Adventure.</p>';
  const edit=!!(current?access.edit:can.create)&&!['live','past','cancelled'].includes(a.lifecycle_status);f.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=!edit);['startAt','endAt','locationName','locationAddress','saveSchedule','saveLocation'].forEach(k=>$(k).disabled=!edit);$('lifecycleCurrent').textContent=label(a.lifecycle_status||'draft');$('nextStatus').innerHTML=(allowed[a.lifecycle_status]||[]).map(s=>`<option value="${s}">${label(s)}</option>`).join('');$('applyTransition').disabled=!current||!access.publish||!$('nextStatus').options.length;
  $('statusHistory').innerHTML=fmtHistory(detail?.statusHistory||[]);$('auditList').innerHTML=fmtHistory(detail?.audit||[]);$('updatesList').innerHTML=(detail?.updates||[]).map(u=>`<article class="adv-update"><strong>${esc(u.title)}</strong> <span class="adv-pill">${esc(u.status)}</span> ${u.pinned?'📌':''}<p>${esc(u.body)}</p><small>${esc(date(u.published_at||u.created_at))}</small> <button class="crew-button" data-update="${esc(u.update_id)}">Edit</button></article>`).join('')||'<p class="adv-muted">No official updates.</p>';
  $('relationshipsList').innerHTML=(detail?.relationships||[]).map(x=>`<article class="adv-update">${esc(x.related_title)} · ${esc(label(x.relationship_type))} <button class="crew-button" data-remove="${esc(x.related_adventure_id)}" data-kind="${esc(x.relationship_type)}">Remove</button></article>`).join('')||'<p class="adv-muted">No related Adventures.</p>';
  $('relatedSelect').innerHTML='<option value="">Choose Adventure</option>'+all.filter(x=>x.adventure_id!==a.adventure_id).map(x=>`<option value="${esc(x.adventure_id)}">${esc(x.title)}</option>`).join('');$('accessList').innerHTML=Object.entries(access).map(([k,v])=>`<p>${esc(label(k))}: <strong>${v?'Allowed':'Restricted'}</strong></p>`).join('');update.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=!current||!access.updates);recap.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=!current||!access.recap);$('relationshipForm').querySelectorAll('input,select,button').forEach(e=>e.disabled=!current||!access.relationships);$('transitionReason').value='';resetUpdate();notify('');tab('overview');$('editor').showModal();}catch(e){banner('listMessage',e.message,'error')}}
  async function reload(message){const id=current?.adventure_id;await list();if(id){await open(id);notify(message)}}
  async function action(run){try{await run()}catch(e){notify(e.message,'error')}}
  $('newAdventure').onclick=()=>open(null);$('closeEditor').onclick=()=>$('editor').close();$('refresh').onclick=list;$('search').oninput=()=>{clearTimeout(window.advSearchTimer);window.advSearchTimer=setTimeout(list,250)};$('filter').onchange=list;
  f.onsubmit=e=>{e.preventDefault();action(async()=>{const d=await post('/crew/adventures/save',formPayload());current={adventure_id:d.adventure_id};await reload('Adventure saved.')})};
  $('saveSchedule').onclick=()=>action(async()=>{await post('/crew/adventures/save',formPayload());await reload('Schedule saved.')});$('saveLocation').onclick=()=>action(async()=>{await post('/crew/adventures/save',formPayload());await reload('Location saved.')});
  $('applyTransition').onclick=()=>action(async()=>{await post('/crew/adventures/transition',{adventure_id:current.adventure_id,status:$('nextStatus').value,reason:$('transitionReason').value});await reload('Lifecycle updated.')});
  recap.onsubmit=e=>{e.preventDefault();action(async()=>{await post('/crew/adventures/recap',{adventure_id:current.adventure_id,...fieldData(recap,['recap_status','recap_title','recap_body','crowd_report'])});await reload('Recap saved.')})};
  function resetUpdate(){update.reset();update.elements.namedItem('update_id').value='';$('updateHeading').textContent='New official update'}$('resetUpdate').onclick=resetUpdate;
  $('updatesList').onclick=e=>{const btn=e.target.closest('button[data-update]');if(!btn)return;const u=detail.updates.find(x=>x.update_id===btn.dataset.update);if(!u)return;setFields(update,u,['update_id','title','body','status','pinned']);$('updateHeading').textContent='Edit official update';};
  update.onsubmit=e=>{e.preventDefault();action(async()=>{await post('/crew/adventures/update',{adventure_id:current.adventure_id,...fieldData(update,['update_id','title','body','status']),pinned:update.elements.namedItem('pinned').checked});await reload('Official update saved.');tab('updates')})};
  $('relationshipForm').onsubmit=e=>{e.preventDefault();action(async()=>{await post('/crew/adventures/relationship',{adventure_id:current.adventure_id,...fieldData($('relationshipForm'),['related_adventure_id','relationship_type'])});await reload('Relationship saved.');tab('relationships')})};
  $('relationshipsList').onclick=e=>{const b=e.target.closest('button[data-remove]');if(!b)return;action(async()=>{await post('/crew/adventures/relationship',{adventure_id:current.adventure_id,related_adventure_id:b.dataset.remove,relationship_type:b.dataset.kind,remove:true});await reload('Relationship removed.');tab('relationships')})};
  await list();
});
