document.addEventListener('DOMContentLoaded',async()=>{
  const session=await OBA_CREW_AUTH.requireCrewSession();if(!session)return;
  OBA_CREW_SHELL.mount({page:'longnecks'});OBA_CREW_SHELL.renderCrewIdentity(session);
  const API=OBA_CREW_AUTH.API_BASE;let selected=null,access={};
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const fmtDate=value=>value?new Date(String(value).endsWith('Z')?value:value+'Z').toLocaleDateString():'—';
  const fmtDateTime=value=>value?new Date(String(value).endsWith('Z')?value:value+'Z').toLocaleString():'—';
  async function call(path,options={}){const r=await fetch(API+path,{credentials:'include',headers:{'Accept':'application/json','Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
  function setFormAvailability(){membershipForm.hidden=!access.manageMembership;chipForm.hidden=!access.adjustRewards;}
  async function load(){const d=await call('/crew/longnecks?q='+encodeURIComponent(search.value));access=d.access||{};setFormAvailability();rows.innerHTML=d.longnecks.map(x=>`<tr data-id="${esc(x.longneck_id)}"><td><strong>${access.viewPrivate?`${esc(x.first_name||'')} ${esc(x.last_name||'')}`.trim():esc(x.display_name||'Longneck')}</strong><br><small>${esc(x.longneck_id)}</small></td><td>${esc(x.display_name||'—')}<br><small>@${esc(x.username||'—')}</small></td><td>${access.viewPrivate?esc(x.email||'—'):'Restricted'}</td><td><strong>${access.viewRewards?`${Number(x.chips||0)} 🍪`:'Restricted'}</strong></td><td>${esc(x.status||'—')}</td><td>${fmtDate(x.created_at)}</td></tr>`).join('')||'<tr><td colspan="6">No Longnecks found.</td></tr>';rows.querySelectorAll('tr[data-id]').forEach(tr=>tr.onclick=()=>openDetail(tr.dataset.id))}
  async function openDetail(id){const d=await call('/crew/longnecks/detail?id='+encodeURIComponent(id));selected=id;access=d.access||access;setFormAvailability();const x=d.longneck;detailTitle.textContent=(x.display_name||'Longneck')+' · @'+(x.username||'—');if(d.membership){membershipTier.value=d.membership.tier||'longneck';membershipStatus.value=d.membership.status||'inactive'}detailGrid.innerHTML=`${access.viewPrivate?`<div><span>Real name</span><strong>${esc(`${x.first_name||''} ${x.last_name||''}`.trim()||'—')}</strong></div><div><span>Email</span><strong>${esc(x.email||'—')}</strong></div>`:''}<div><span>Status</span><strong>${esc(x.status||'—')}</strong></div>${access.viewRewards?`<div><span>Chips</span><strong>${Number(d.chips||0)} 🍪</strong></div>`:''}${access.viewPrivate?`<div><span>Email verified</span><strong>${x.email_verified_at?'Yes':'No'}</strong></div><div><span>Marketing email</span><strong>${x.marketing_email?'On':'Off'}</strong></div>`:''}<div><span>Joined</span><strong>${fmtDate(x.created_at)}</strong></div>${access.viewPrivate?`<div><span>Last login</span><strong>${fmtDateTime(x.last_login_at)}</strong></div>`:''}`;detailLedger.innerHTML=access.viewRewards?(d.ledger.map(t=>`<div class="ln-ledger-row"><span>${esc(t.description)}<br><small>${fmtDateTime(t.created_at)}</small></span><strong>${Number(t.amount)>0?'+':''}${Number(t.amount)}</strong></div>`).join('')||'<p>No Chip activity.</p>'):'<p>Reward history is restricted for your Crew access.</p>';detailDialog.showModal()}
  searchBtn.onclick=load;refresh.onclick=load;closeDialog.onclick=()=>detailDialog.close();
  membershipForm.onsubmit=async e=>{e.preventDefault();if(!selected||!access.manageMembership)return;try{await call('/crew/longnecks/membership',{method:'POST',body:JSON.stringify({longneckId:selected,tier:membershipTier.value,status:membershipStatus.value})});await openDetail(selected)}catch(x){alert(x.message)}};
  chipForm.onsubmit=async e=>{e.preventDefault();if(!selected||!access.adjustRewards)return;try{await call('/crew/longnecks/chips',{method:'POST',body:JSON.stringify({longneckId:selected,amount:Number(chipAmount.value),note:chipNote.value})});chipAmount.value='';chipNote.value='';await openDetail(selected);await load()}catch(x){alert(x.message)}};
  await load();
});
