document.addEventListener('DOMContentLoaded',async()=>{
  const session=await OBA_CREW_AUTH.requireCrewSession();if(!session)return;
  OBA_CREW_SHELL.mount({page:'longnecks'});OBA_CREW_SHELL.renderCrewIdentity(session);
  const API=OBA_CREW_AUTH.API_BASE, esc=OBA_CREW_CORE.esc;let selected=null,current=null,access={};
  const $=id=>document.getElementById(id);const fmt=v=>v?new Date(String(v).endsWith('Z')?v:v+'Z').toLocaleString():'—';const date=v=>v?new Date(String(v).endsWith('Z')?v:v+'Z').toLocaleDateString():'—';
  async function call(path,options={}){return OBA_CREW_CORE.api(path,options)}
  function msg(text,bad=false){detailMessage.hidden=!text;detailMessage.className='ln-message '+(bad?'crew-message error':'crew-message success');detailMessage.textContent=text||''}
  function post(path,body){return call(path,{method:'POST',body:JSON.stringify(body)})}
  function activateTab(name){document.querySelectorAll('.ln-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.ln-section').forEach(s=>s.classList.toggle('active',s.dataset.section===name))}
  recordTabs.addEventListener('click',e=>{const b=e.target.closest('.ln-tab');if(b)activateTab(b.dataset.tab)});
  function availability(){identityForm.hidden=!access.editIdentity;accountForm.hidden=!access.manageAccount;consentForm.hidden=!access.managePreferences;wantedForm.hidden=!access.managePreferences;faveForm.hidden=!access.manageFaves;membershipForm.hidden=!access.manageMembership;chipForm.hidden=!access.adjustRewards;noteForm.hidden=!access.manageNotes}
  async function load(){const d=await call('/crew/longnecks?q='+encodeURIComponent(search.value));rows.innerHTML=d.longnecks.map(x=>`<tr data-id="${esc(x.longneck_id)}"><td><strong>${d.access.viewPrivate?esc(`${x.first_name||''} ${x.last_name||''}`.trim()):esc(x.display_name||'Longneck')}</strong><br><small>${esc(x.longneck_id)}</small></td><td>${esc(x.display_name||'—')}<br><small>@${esc(x.username||'—')}</small></td><td>${d.access.viewPrivate?esc(x.email||'—'):'Restricted'}</td><td><strong>${d.access.viewRewards?`${Number(x.chips||0)} 🍪`:'Restricted'}</strong></td><td>${esc(x.status||'—')}</td><td>${date(x.created_at)}</td></tr>`).join('')||'<tr><td colspan="6">No Longnecks found.</td></tr>';rows.querySelectorAll('tr[data-id]').forEach(tr=>tr.onclick=()=>openDetail(tr.dataset.id))}
  function renderHistory(items){historyList.innerHTML=items.map(h=>{let prev='',next='';try{prev=h.previous_state_json?JSON.stringify(JSON.parse(h.previous_state_json)):''}catch{}try{next=h.new_state_json?JSON.stringify(JSON.parse(h.new_state_json)):''}catch{}return `<div class="ln-row"><span><strong>${esc(h.action.replaceAll('_',' '))}</strong><br>${esc(h.reason||'No reason recorded')}<br><small>${esc(h.actor_type)} ${esc(h.actor_id||'system')} · ${fmt(h.created_at)}</small>${prev||next?`<br><small>${esc(prev)} → ${esc(next)}</small>`:''}</span></div>`}).join('')||'<p class="ln-muted">No canonical history yet.</p>'}
  function render(d){current=d;access=d.access||{};availability();const x=d.longneck;detailTitle.textContent=`${x.display_name||'Longneck'} · @${x.username||'—'}`;recordMeta.innerHTML=`<span class="ln-pill">${esc(x.longneck_id)}</span><span class="ln-pill">${esc(x.status)}</span>${access.viewRewards?`<span class="ln-pill">${Number(d.chips||0)} Chips</span>`:''}`;overviewGrid.innerHTML=`${access.viewPrivate?`<div class="ln-field"><label>Real name</label><div class="ln-read">${esc(`${x.first_name||''} ${x.last_name||''}`.trim()||'—')}</div></div><div class="ln-field"><label>Email</label><div class="ln-read">${esc(x.email||'—')}</div></div>`:''}<div class="ln-field"><label>Public identity</label><div class="ln-read">${esc(x.display_name||'—')} · @${esc(x.username||'—')}</div></div><div class="ln-field"><label>Joined</label><div class="ln-read">${date(x.created_at)}</div></div>${access.viewPrivate?`<div class="ln-field"><label>Email verified</label><div class="ln-read">${x.email_verified_at?'Yes':'No'}</div></div><div class="ln-field"><label>Last login</label><div class="ln-read">${fmt(x.last_login_at)}</div></div>`:''}`;provenance.innerHTML=`<p class="ln-muted">Created ${fmt(x.created_at)}<br>Last record update ${fmt(x.updated_at)}</p>`;attention.innerHTML=`${access.viewPrivate&&!x.email_verified_at?'<div class="ln-warning">Email needs verification.</div>':'<p class="ln-muted">No immediate record warnings.</p>'}`;
    if(access.viewPrivate){identityFirst.value=x.first_name||'';identityLast.value=x.last_name||'';identityDisplay.value=x.display_name||'';identityUsername.value=x.username||'';identityEmail.value=x.email||'';identityAvatar.value=x.avatar_key||'olly';accountStatus.value=x.status==='deactivated'?'deactivated':'active';prefEmail.checked=!!x.marketing_email;prefSms.checked=!!x.marketing_sms}
    const p=d.preferences||{};wantedStyle.value=p.notification_style||'1-star';wantedDrops.checked=!!p.weekly_drops;wantedFlavors.checked=!!p.new_flavors;wantedWatch.checked=!!p.cookie_watch;wantedBertha.checked=!!p.bertha_open;wantedEvents.checked=!!p.markets_events;wantedBulletin.checked=!!p.bulletin_email;
    if(d.membership){membershipTier.value=d.membership.tier||'longneck';membershipStatus.value=d.membership.status||'inactive'}
    detailLedger.innerHTML=access.viewRewards?(d.ledger.map(t=>`<div class="ln-row"><span>${esc(t.description)}<br><small>${fmt(t.created_at)} · ${esc(t.transaction_type)}</small></span><strong>${Number(t.amount)>0?'+':''}${Number(t.amount)}</strong></div>`).join('')||'<p class="ln-muted">No Chip activity.</p>'):'<p class="ln-muted">Reward history restricted.</p>';
    favesList.innerHTML=(d.faves||[]).map(f=>`<div class="ln-row"><span><strong>${esc(f.cookie_name||f.cookie_id)}</strong><br><small>${esc(f.cookie_slug||'')}</small></span>${access.manageFaves?`<button class="crew-button soft" data-remove-fave="${esc(f.cookie_id)}" data-name="${esc(f.cookie_name||'')}" data-slug="${esc(f.cookie_slug||'')}">Remove</button>`:''}</div>`).join('')||'<p class="ln-muted">No Flavor Faves yet.</p>';
    notesList.innerHTML=access.manageNotes?(d.notes.map(n=>`<div class="ln-row"><span>${esc(n.note_text)}<br><small>Crew ${esc(n.created_by_crew_user_id)} · ${fmt(n.created_at)}</small></span></div>`).join('')||'<p class="ln-muted">No internal notes.</p>'):'<p class="ln-muted">Internal notes restricted.</p>';
    accessList.innerHTML=Object.entries(access).map(([k,v])=>`<div class="ln-row"><span>${esc(k)}</span><strong>${v?'Allowed':'Restricted'}</strong></div>`).join('');renderHistory(d.history||[])
  }
  async function refreshDetail(){if(!selected)return;const d=await call('/crew/longnecks/detail?id='+encodeURIComponent(selected));render(d)}
  async function openDetail(id){selected=id;msg('');await refreshDetail();activateTab('overview');detailDialog.showModal()}
  closeDialog.onclick=()=>{selected=null;current=null;detailDialog.close()};detailDialog.addEventListener('cancel',()=>{selected=null;current=null});
  searchBtn.onclick=load;refresh.onclick=load;
  identityForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/identity',{longneckId:selected,firstName:identityFirst.value,lastName:identityLast.value,displayName:identityDisplay.value,username:identityUsername.value,email:identityEmail.value,avatarKey:identityAvatar.value,reason:identityReason.value,password:identityPassword.value});identityReason.value='';identityPassword.value='';await refreshDetail();msg('Identity correction saved and audited.')}catch(x){msg(x.message,true)}};
  accountForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/account-status',{longneckId:selected,status:accountStatus.value,reason:accountReason.value,password:accountPassword.value});accountReason.value='';accountPassword.value='';await refreshDetail();await load();msg('Account status updated and audited.')}catch(x){msg(x.message,true)}};
  consentForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/preferences',{longneckId:selected,marketingEmail:prefEmail.checked,marketingSms:prefSms.checked,reason:consentReason.value});consentReason.value='';await refreshDetail();msg('Communication correction saved.')}catch(x){msg(x.message,true)}};
  wantedForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/notification-preferences',{longneckId:selected,notificationStyle:wantedStyle.value,weeklyDrops:wantedDrops.checked,newFlavors:wantedFlavors.checked,cookieWatch:wantedWatch.checked,berthaOpen:wantedBertha.checked,marketsEvents:wantedEvents.checked,bulletinEmail:wantedBulletin.checked,reason:wantedReason.value});wantedReason.value='';await refreshDetail();msg('Most Wanted preferences saved and audited.')}catch(x){msg(x.message,true)}};
  membershipForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/membership',{longneckId:selected,tier:membershipTier.value,status:membershipStatus.value,reason:membershipReason.value});membershipReason.value='';await refreshDetail();msg('Membership updated and audited.')}catch(x){msg(x.message,true)}};
  chipForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/chips',{longneckId:selected,amount:Number(chipAmount.value),note:chipNote.value});chipAmount.value='';chipNote.value='';await refreshDetail();await load();msg('Chip correction appended and audited.')}catch(x){msg(x.message,true)}};
  noteForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/note',{longneckId:selected,note:noteText.value});noteText.value='';await refreshDetail();msg('Internal note added.')}catch(x){msg(x.message,true)}};
  faveForm.onsubmit=async e=>{e.preventDefault();try{await post('/crew/longnecks/faves',{longneckId:selected,action:'add',cookieId:faveId.value,cookieName:faveName.value,cookieSlug:faveSlug.value,reason:faveReason.value});faveId.value=faveName.value=faveSlug.value=faveReason.value='';await refreshDetail();msg('Flavor Fave corrected.')}catch(x){msg(x.message,true)}};
  favesList.addEventListener('click',async e=>{const b=e.target.closest('[data-remove-fave]');if(!b)return;const reason=prompt('Required support reason for removing this Flavor Fave:');if(!reason)return;try{await post('/crew/longnecks/faves',{longneckId:selected,action:'remove',cookieId:b.dataset.removeFave,cookieName:b.dataset.name,cookieSlug:b.dataset.slug,reason});await refreshDetail();msg('Flavor Fave removed and audited.')}catch(x){msg(x.message,true)}});
  await load();
});