(() => {
'use strict';
const API_BASE='https://api.ollysbakedassortments.com';
const $=id=>document.getElementById(id); let session=null,permissions={},reviews=[],cookies=[],current=null,canEdit=false,canChangeAccess=false,trashMode=false;
const can=key=>String(session?.user?.role||'').toLowerCase()==='owner'||permissions[key]===true;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Date(String(d).replace(' ','T')+'Z').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
async function api(path,options={}){const r=await fetch(API_BASE+path,{credentials:'include',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{}if(!r.ok||d.ok!==true){const e=new Error(d.error||`Request failed (${r.status}).`);e.data=d;e.status=r.status;throw e}return d}
function message(text,type=''){const el=$('pageMessage');el.hidden=!text;el.className=text?`review-alert ${type}`:'';el.textContent=text||''}
function dialogMessage(text,type=''){const el=$('dialogMessage');el.hidden=!text;el.className=text?`review-alert ${type}`:'';el.textContent=text||''}
function countMap(rows){return Object.fromEntries((rows||[]).map(r=>[r.status,Number(r.count)]))}
function queueItem(r){return `<button class="workflow-item" type="button" data-queue-review="${esc(r.review_id)}"><span><strong>${esc(r.review_id)} · ${esc(r.reviewer_name||'Unnamed reviewer')}</strong><small>${esc(r.source||'—')} · ${'★'.repeat(Number(r.rating)||0)}</small></span><span class="review-badge ${esc(r.status)}">${esc(r.status)}</span></button>`}
function queueGroup(key,title,description,rows){return `<button class="workflow-group workflow-group-button${rows.length?'':' empty'}" type="button" data-queue-key="${esc(key)}" ${rows.length?'':'disabled'}><span class="workflow-group-copy"><strong>${esc(title)}</strong><small>${esc(description)}</small></span><span class="workflow-group-count">${rows.length}</span></button>`}
let queueSets={};
function renderOverview(data){const c=countMap(data.counts);$('kpiRough').textContent=c.rough||0;$('kpiFinal').textContent=c.final||0;$('kpiVerified').textContent=c.verified||0;$('kpiPublished').textContent=c.published||0;$('kpiTrash').textContent=c.trash||0;const mine=data.myQueue||[],team=data.teamQueue||[];queueSets={myRough:{title:'Returned / Rough Imports',description:'Continue or correct your Rough review records.',eyebrow:'MY REVIEW WORKFLOW',rows:mine.filter(r=>r.status==='rough')},myFinal:{title:'My Final Reviews',description:'Finalized and awaiting verification.',eyebrow:'MY REVIEW WORKFLOW',rows:mine.filter(r=>r.status==='final')},myVerified:{title:'My Verified Reviews',description:'Your reviews that passed verification, including Published reviews.',eyebrow:'MY REVIEW WORKFLOW',rows:mine.filter(r=>r.status==='verified'||r.status==='published')},teamFinal:{title:'Awaiting Verification',description:'Final reviews in the shared Manager queue.',eyebrow:'TEAM WORKFLOW',rows:team.filter(r=>r.status==='final')},teamVerified:{title:'Awaiting Publication',description:'Verified reviews waiting for publication.',eyebrow:'TEAM WORKFLOW',rows:team.filter(r=>r.status==='verified')},teamRough:{title:'Rough Imports',description:'Shared Rough imports available across the Crew.',eyebrow:'TEAM WORKFLOW',rows:team.filter(r=>r.status==='rough')}};$('myQueue').innerHTML=[queueGroup('myRough',queueSets.myRough.title,queueSets.myRough.description,queueSets.myRough.rows),queueGroup('myFinal',queueSets.myFinal.title,queueSets.myFinal.description,queueSets.myFinal.rows),queueGroup('myVerified',queueSets.myVerified.title,queueSets.myVerified.description,queueSets.myVerified.rows)].join('');$('teamQueue').innerHTML=[queueGroup('teamFinal',queueSets.teamFinal.title,queueSets.teamFinal.description,queueSets.teamFinal.rows),queueGroup('teamVerified',queueSets.teamVerified.title,queueSets.teamVerified.description,queueSets.teamVerified.rows),queueGroup('teamRough',queueSets.teamRough.title,queueSets.teamRough.description,queueSets.teamRough.rows)].join('');$('viewTrash').hidden=trashMode||!data.trashVisible;$('viewActive').hidden=!trashMode}

function openQueue(key){const q=queueSets[key];if(!q||!q.rows.length)return;$('queueEyebrow').textContent=q.eyebrow;$('queueTitle').textContent=q.title;$('queueDescription').textContent=q.description;$('queueSheetList').innerHTML=q.rows.map(queueItem).join('');$('queueDialog').showModal()}
function renderRows(){const q=$('reviewSearch').value.trim().toLowerCase(),src=$('sourceFilter').value;const filtered=reviews.filter(r=>(src==='all'||r.source===src)&&(!q||[r.reviewId,r.reviewerName,r.source,r.reviewType,r.accessScope,...r.cookieNames].join(' ').toLowerCase().includes(q)));$('reviewRows').innerHTML=filtered.length?filtered.map(r=>`<tr data-review-id="${esc(r.reviewId)}"><td><strong>${esc(r.reviewId)}</strong></td><td>${esc(r.reviewerName||'—')}</td><td class="stars" aria-label="${r.rating} out of 5 stars">${'★'.repeat(r.rating||0)}</td><td>${esc(r.source||'—')}</td><td>${r.reviewType==='cookie'?'Cookie':'OBA'}</td><td>${esc(r.cookieNames.join(', ')||'—')}</td><td><span class="review-badge ${esc(r.status)}">${esc(r.status)}</span> <span class="review-badge ${esc(r.accessScope)}">${esc(r.accessScope)}</span></td><td>${esc(fmt(r.reviewDate))}</td><td>${esc(r.importedBy||'—')}</td><td>${esc(fmt(r.updatedAt))}</td></tr>`).join(''):`<tr><td colspan="10" class="review-empty">No reviews match this view.</td></tr>`}
function renderStats(data){const s=data.scopes||{};const val=(n,a)=>n?`${a??'—'} (${n})`:'—';$('obaStats').innerHTML=[['Reviews',s.final_count||0,s.verified_count||0,s.published_count||0],['Average Rating',s.final_avg??'—',s.verified_avg??'—',s.published_avg??'—'],['5-Star Reviews','—','—',s.published_five_star||0],['Written Reviews','—','—',s.published_written||0],['Google','—','—',s.published_google||0],['Hotplate','—','—',s.published_hotplate||0]].map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('');$('cookieStats').innerHTML=(data.cookies||[]).length?(data.cookies||[]).map(r=>`<tr><td><strong>${esc(r.cookie.name)}</strong><small style="display:block">${esc(r.cookie_id)}</small></td><td>${esc(val(Number(r.public_count),r.public_avg))}</td><td>${esc(val(Number(r.verified_count),r.verified_avg))}</td><td>${esc(val(Number(r.final_count),r.final_avg))}</td><td>${esc(fmt(r.latest_review_date))}</td></tr>`).join(''):`<tr><td colspan="5" class="review-empty">Cookie review statistics will appear after reviews are linked.</td></tr>`}
async function loadAll(){message('');try{const status=trashMode?'trash':$('statusFilter').value;const [overview,list,stat]=await Promise.all([api('/crew/reviews/overview'),api(`/crew/reviews?status=${encodeURIComponent(status)}`),api('/crew/reviews/stats')]);permissions=list.permissions||permissions;reviews=list.reviews||[];renderOverview(overview);renderRows();renderStats(stat);$('importReview').hidden=!can('reviews.import');$('statusFilter').disabled=trashMode}catch(e){message(e.message,'error')}}
function selectedCookies(){return [...document.querySelectorAll('#cookiePicker input:checked')].map(x=>x.value)}
function selectedImages(){return [...document.querySelectorAll('.review-photo-path')].map(x=>x.value.trim()).filter(Boolean)}
function photoRow(path=''){const safe=esc(path);return `<div class="review-photo-row"><div class="review-photo-preview">${path?`<img src="/${safe}" alt="Review photo preview" loading="lazy">`:'<span>No preview</span>'}</div><input class="crew-input review-photo-path" value="${safe}" placeholder="images/reviews/example.png" aria-label="Review photo path"><button class="crew-button soft review-photo-remove" type="button" aria-label="Remove review photo">Remove</button></div>`}
function renderPhotos(paths=[]){$('reviewPhotoList').innerHTML=(paths||[]).map(photoRow).join('');$('addReviewPhoto').hidden=!!current&&!canEdit;document.querySelectorAll('.review-photo-remove').forEach(b=>b.hidden=!!current&&!canEdit)}
function formData(){return{reviewId:current?.reviewId||null,recordVersion:current?.recordVersion||null,source:$('source').value,sourceUrl:$('sourceUrl').value.trim(),reviewDate:$('reviewDate').value,reviewerName:$('reviewerName').value.trim(),rating:Number($('rating').value)||null,originalReviewText:$('reviewText').value,reviewType:$('reviewType').value,featuredPriority:Number($('featuredPriority').value)||0,internalNotes:$('internalNotes').value,cookieIds:selectedCookies(),imagePaths:selectedImages(),note:$('actionNote').value.trim()}}
function setFormDisabled(disabled){document.querySelectorAll('#reviewForm input,#reviewForm select,#reviewForm textarea').forEach(el=>{if(el.id!=='actionNote')el.disabled=disabled})}
function button(label,action,cls='crew-button'){return `<button class="${cls}" type="button" data-review-action="${action}">${label}</button>`}
function renderAccess(){const field=$('accessField');if(!current||current.status==='trash'){field.hidden=true;return}field.hidden=false;const scope=current.accessScope||'shared';$('accessBadge').textContent=scope==='shared'?'Shared':'Private';$('accessBadge').className=`review-badge ${scope}`;$('toggleAccess').textContent=scope==='shared'?'Make Private':'Make Shared';$('toggleAccess').hidden=!canChangeAccess}
function renderActions(){const left=[],right=[];if(!current){right.push(button('Save Rough','import','crew-button primary'));}else{if(canEdit){right.push(button('Save Changes','save','crew-button'));if(current.status==='rough'&&can('reviews.finalize'))right.push(button('Mark Final','finalize','crew-button primary'));if(current.status==='final'&&can('reviews.edit_final'))left.push(button('Return to Rough','return'));if(current.status==='verified'&&can('reviews.edit_verified'))left.push(button('Revoke Verification','revoke_verification'));if(current.status==='published'&&can('reviews.unpublish'))left.push(button('Unpublish','unpublish'));if(current.status!=='trash')left.push(button('Move to Trash','trash','crew-button danger-button'));}if(current.status==='final'&&can('reviews.verify'))right.push(button('Verify','verify','crew-button primary'));if(current.status==='verified'&&can('reviews.publish'))right.push(button('Publish','publish','crew-button primary'));if(current.status==='trash'&&can('reviews.trash_restore'))right.push(button('Restore as Rough','restore','crew-button primary'));if(current.status==='trash'&&can('reviews.permanent_delete'))left.push(button('Permanent Delete','permanent_delete','crew-button danger-button'));}$('leftActions').innerHTML=left.join('');$('rightActions').innerHTML=right.join('');renderAccess()}
function needsNote(action){return['save','return','verify','revoke_verification','unpublish','trash','restore','permanent_delete','access'].includes(action)}
function showNote(required){$('noteWrap').hidden=!required;if(required)$('actionNote').focus()}
async function loadAudit(reviewId){if(!can('reviews.view_audit')){$('auditSection').hidden=true;return}try{const d=await api(`/crew/reviews/audit?reviewId=${encodeURIComponent(reviewId)}`);$('auditSection').hidden=false;$('auditList').innerHTML=(d.events||[]).map(e=>`<div class="audit-event"><strong>${esc(String(e.action||'').replaceAll('_',' '))}</strong><small>${esc(e.actor_name||e.actor_email||'System')} · ${esc(fmt(e.performed_at))}${e.from_status||e.to_status?` · ${esc(e.from_status||'—')} → ${esc(e.to_status||'—')}`:''}</small>${e.note?`<p>${esc(e.note)}</p>`:''}</div>`).join('')||'<div class="review-empty">No audit events yet.</div>'}catch{$('auditSection').hidden=true}}
function populateForm(r){current=r||null;dialogMessage('');$('actionNote').value='';$('noteWrap').hidden=true;$('dialogEyebrow').textContent=r?'REVIEW RECORD':'IMPORT REVIEW';$('dialogTitle').textContent=r?r.reviewId:'Import Review';const role=String(session?.user?.role||'').toLowerCase();const defaultAccess=role==='crew'?'Shared':'Private';$('recordMeta').textContent=r?`${r.status.toUpperCase()} · ${String(r.accessScope||'shared').toUpperCase()} · Version ${r.recordVersion} · Imported ${fmt(r.importedAt)}`:`New ${defaultAccess} Rough · customer-facing publication is controlled separately.`;$('source').value=r?.source||'';$('sourceUrl').value=r?.sourceUrl||'';$('reviewDate').value=r?.reviewDate||'';$('reviewerName').value=r?.reviewerName||'';$('rating').value=r?.rating||'';$('reviewText').value=r?.originalReviewText||'';$('reviewType').value=r?.reviewType||'business';$('featuredPriority').value=r?.featuredPriority||0;$('internalNotes').value=r?.internalNotes||'';document.querySelectorAll('#cookiePicker input').forEach(x=>x.checked=(r?.cookieIds||[]).includes(x.value));renderPhotos(r?.imagePaths||[]);setFormDisabled(r?!canEdit:false);renderActions();if(r)loadAudit(r.reviewId);else{$('auditSection').hidden=true;$('accessField').hidden=true}$('reviewDialog').showModal()}
async function openReview(id){try{const d=await api(`/crew/reviews/record?reviewId=${encodeURIComponent(id)}`);canEdit=d.canEdit===true;canChangeAccess=d.canChangeAccess===true;permissions=d.permissions||permissions;populateForm(d.review)}catch(e){message(e.message,'error')}}
async function perform(action){dialogMessage('');const note=$('actionNote').value.trim();if(needsNote(action)&&!note){showNote(true);dialogMessage('A note/reason is required for this action.','error');return}try{let d;if(action==='import'){const payload=formData();try{d=await api('/crew/reviews/import',{method:'POST',body:JSON.stringify(payload)})}catch(e){if(e.data?.code!=='POSSIBLE_DUPLICATE')throw e;const match=e.data?.warnings?.find(w=>w.code==='possible_duplicate');const existing=match?.reviewId||'an existing review';if(!confirm(`Possible duplicate detected: ${existing}.\n\nReview the existing record before continuing.\n\nChoose OK only if this is a separate legitimate review and you intentionally want to import it anyway.`)){dialogMessage(`Import stopped. Check ${existing} before continuing.`,'error');return}d=await api('/crew/reviews/import',{method:'POST',body:JSON.stringify({...payload,duplicateAcknowledged:true})})}}else if(action==='save')d=await api('/crew/reviews/save',{method:'POST',body:JSON.stringify(formData())});else if(action==='access'){const accessScope=(current.accessScope||'shared')==='shared'?'private':'shared';d=await api('/crew/reviews/access',{method:'POST',body:JSON.stringify({reviewId:current.reviewId,recordVersion:current.recordVersion,accessScope,note})})}else if(action==='permanent_delete'){if(!confirm(`Permanently delete ${current.reviewId}? This cannot be restored from the Reviews Manager.`))return;d=await api('/crew/reviews/permanent-delete',{method:'POST',body:JSON.stringify({reviewId:current.reviewId,recordVersion:current.recordVersion,note})})}else{if(action==='trash'&&!confirm(`Move ${current.reviewId} to Trash? You may lose access to it after this action.`))return;d=await api('/crew/reviews/action',{method:'POST',body:JSON.stringify({reviewId:current.reviewId,recordVersion:current.recordVersion,action,note})})}dialogMessage(action==='import'?`${d.reviewId} imported as Rough.`:'Review updated.','success');await loadAll();if(action==='permanent_delete'){setTimeout(()=>$('reviewDialog').close(),350);return}if(d.reviewId)setTimeout(()=>openReview(d.reviewId),250)}catch(e){if(e.data?.code==='STALE_REVIEW')dialogMessage('This review changed while you were working on it. Close and reopen the record to refresh it.','error');else dialogMessage(e.message,'error')}}
async function init(){session=await window.OBA_CREW_AUTH.requireCrewSession();if(!session)return;window.OBA_CREW_SHELL.mount({activePage:'reviews'});window.OBA_CREW_SHELL.renderCrewIdentity(session);permissions=session.user?.effectivePermissions||{};if(!can('reviews.view')){message('Your Crew account does not have access to Reviews.','error');$('importReview').hidden=true;return}const c=await api('/crew/reviews/cookies');cookies=c.cookies||[];$('cookiePicker').innerHTML=cookies.map(c=>`<label class="cookie-choice"><input type="checkbox" value="${esc(c.cookieId)}"><span>${esc(c.name)} <small>${esc(c.cookieId)}</small></span></label>`).join('');await loadAll()}
$('refreshReviews').addEventListener('click',loadAll);$('importReview').addEventListener('click',()=>{canEdit=true;canChangeAccess=false;populateForm(null)});$('closeDialog').addEventListener('click',()=>$('reviewDialog').close());$('closeQueueDialog').addEventListener('click',()=>$('queueDialog').close());$('reviewSearch').addEventListener('input',renderRows);$('sourceFilter').addEventListener('change',renderRows);$('statusFilter').addEventListener('change',()=>{trashMode=false;loadAll()});$('viewTrash').addEventListener('click',()=>{trashMode=true;loadAll()});$('viewActive').addEventListener('click',()=>{trashMode=false;$('statusFilter').value='active';loadAll()});$('reviewRows').addEventListener('click',e=>{const tr=e.target.closest('tr[data-review-id]');if(tr)openReview(tr.dataset.reviewId)});document.addEventListener('click',e=>{const group=e.target.closest('[data-queue-key]');if(group){openQueue(group.dataset.queueKey);return}const q=e.target.closest('[data-queue-review]');if(q){$('queueDialog').close();openReview(q.dataset.queueReview);return}if(e.target.closest('#toggleAccess')){if($('noteWrap').hidden){showNote(true);dialogMessage('A note/reason is required before changing Crew access.','error');return}perform('access');return}const b=e.target.closest('[data-review-action]');if(!b)return;const a=b.dataset.reviewAction;if(needsNote(a)&&$('noteWrap').hidden){showNote(true);return}perform(a)});$('addReviewPhoto').addEventListener('click',()=>{if(current&&!canEdit)return;const rows=document.querySelectorAll('.review-photo-row');if(rows.length>=6){dialogMessage('A review can have up to 6 photos.','error');return}$('reviewPhotoList').insertAdjacentHTML('beforeend',photoRow(''))});$('reviewPhotoList').addEventListener('click',e=>{const b=e.target.closest('.review-photo-remove');if(!b||current&&!canEdit)return;b.closest('.review-photo-row')?.remove()});$('reviewPhotoList').addEventListener('input',e=>{if(!e.target.classList.contains('review-photo-path'))return;const row=e.target.closest('.review-photo-row'),preview=row?.querySelector('.review-photo-preview');if(preview){const path=e.target.value.trim();preview.innerHTML=path?`<img src="/${esc(path)}" alt="Review photo preview" loading="lazy">`:'<span>No preview</span>'}});$('reviewType').addEventListener('change',()=>{if($('reviewType').value==='business')document.querySelectorAll('#cookiePicker input').forEach(x=>x.checked=false)});document.addEventListener('DOMContentLoaded',init);
})();
