(() => {
'use strict';
const API_BASE='https://api.ollysbakedassortments.com';
const $=id=>document.getElementById(id); let session=null,permissions={},reviews=[],cookies=[],stats=null,current=null,canEdit=false,trashMode=false;
const can=key=>String(session?.user?.role||'').toLowerCase()==='owner'||permissions[key]===true;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Date(String(d).replace(' ','T')+'Z').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
async function api(path,options={}){const r=await fetch(API_BASE+path,{credentials:'include',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{}if(!r.ok||d.ok!==true){const e=new Error(d.error||`Request failed (${r.status}).`);e.data=d;e.status=r.status;throw e}return d}
function message(text,type=''){const el=$('pageMessage');el.hidden=!text;el.className=text?`review-alert ${type}`:'';el.textContent=text||''}
function dialogMessage(text,type=''){const el=$('dialogMessage');el.hidden=!text;el.className=text?`review-alert ${type}`:'';el.textContent=text||''}
function countMap(rows){return Object.fromEntries((rows||[]).map(r=>[r.status,Number(r.count)]))}
function renderOverview(data){const c=countMap(data.counts),m=countMap(data.myCounts),t=countMap(data.teamCounts);$('kpiRough').textContent=c.rough||0;$('kpiFinal').textContent=c.final||0;$('kpiVerified').textContent=c.verified||0;$('kpiPublished').textContent=c.published||0;$('kpiTrash').textContent=c.trash||0;$('myQueue').innerHTML=[['Returned / Rough Imports',m.rough||0,'Continue or correct your Rough review records.'],['My Final Reviews',m.final||0,'Finalized and awaiting verification.'],['My Verified Reviews',m.verified||0,'Verified and awaiting publication/progression.']].map(([a,b,c])=>`<div class="workflow-row"><div><strong>${esc(a)}</strong><small>${esc(c)}</small></div><strong>${b}</strong></div>`).join('');$('teamQueue').innerHTML=[['Awaiting Verification',t.final||0,'Final reviews in the shared Manager queue.'],['Awaiting Publication',t.verified||0,'Verified reviews waiting for publication.'],['Rough Imports',c.rough||0,'Active work-in-progress imports.']].map(([a,b,c])=>`<div class="workflow-row"><div><strong>${esc(a)}</strong><small>${esc(c)}</small></div><strong>${b}</strong></div>`).join('');$('viewTrash').hidden=!data.trashVisible}
function renderRows(){const q=$('reviewSearch').value.trim().toLowerCase(),src=$('sourceFilter').value;const filtered=reviews.filter(r=>(src==='all'||r.source===src)&&(!q||[r.reviewId,r.reviewerName,r.source,r.reviewType,...r.cookieNames].join(' ').toLowerCase().includes(q)));$('reviewRows').innerHTML=filtered.length?filtered.map(r=>`<tr data-review-id="${esc(r.reviewId)}"><td><strong>${esc(r.reviewId)}</strong></td><td>${esc(r.reviewerName||'—')}</td><td class="stars" aria-label="${r.rating} out of 5 stars">${'★'.repeat(r.rating||0)}</td><td>${esc(r.source||'—')}</td><td>${r.reviewType==='cookie'?'Cookie':'OBA'}</td><td>${esc(r.cookieNames.join(', ')||'—')}</td><td><span class="review-badge ${esc(r.status)}">${esc(r.status)}</span></td><td>${esc(fmt(r.reviewDate))}</td><td>${esc(r.importedBy||'—')}</td><td>${esc(fmt(r.updatedAt))}</td></tr>`).join(''):`<tr><td colspan="10" class="review-empty">No reviews match this view.</td></tr>`}
function renderStats(data){stats=data;const s=data.scopes||{};const val=(n,a)=>n?`${a??'—'} (${n})`:'—';$('obaStats').innerHTML=[['Reviews',s.final_count||0,s.verified_count||0,s.published_count||0],['Average Rating',s.final_avg??'—',s.verified_avg??'—',s.published_avg??'—'],['5-Star Reviews','—','—',s.published_five_star||0],['Written Reviews','—','—',s.published_written||0],['Google','—','—',s.published_google||0],['Hotplate','—','—',s.published_hotplate||0]].map(r=>`<tr>${r.map((x,i)=>`<td>${i===0?esc(x):esc(x)}</td>`).join('')}</tr>`).join('');$('cookieStats').innerHTML=(data.cookies||[]).length?(data.cookies||[]).map(r=>`<tr><td><strong>${esc(r.cookie.name)}</strong><small style="display:block">${esc(r.cookie_id)}</small></td><td>${esc(val(Number(r.public_count),r.public_avg))}</td><td>${esc(val(Number(r.verified_count),r.verified_avg))}</td><td>${esc(val(Number(r.final_count),r.final_avg))}</td><td>${esc(fmt(r.latest_review_date))}</td></tr>`).join(''):`<tr><td colspan="5" class="review-empty">Cookie review statistics will appear after reviews are linked.</td></tr>`}
async function loadAll(){message('');try{const status=trashMode?'trash':$('statusFilter').value;const [overview,list,stat]=await Promise.all([api('/crew/reviews/overview'),api(`/crew/reviews?status=${encodeURIComponent(status)}`),api('/crew/reviews/stats')]);permissions=list.permissions||permissions;reviews=list.reviews||[];renderOverview(overview);renderRows();renderStats(stat);$('importReview').hidden=!can('reviews.import')}catch(e){message(e.message,'error')}}
function selectedCookies(){return [...document.querySelectorAll('#cookiePicker input:checked')].map(x=>x.value)}
function formData(){return{reviewId:current?.reviewId||null,recordVersion:current?.recordVersion||null,source:$('source').value,sourceUrl:$('sourceUrl').value.trim(),reviewDate:$('reviewDate').value,reviewerName:$('reviewerName').value.trim(),rating:Number($('rating').value)||null,originalReviewText:$('reviewText').value,reviewType:$('reviewType').value,featuredPriority:Number($('featuredPriority').value)||0,internalNotes:$('internalNotes').value,cookieIds:selectedCookies(),note:$('actionNote').value.trim()}}
function setFormDisabled(disabled){document.querySelectorAll('#reviewForm input,#reviewForm select,#reviewForm textarea').forEach(el=>{if(el.id!=='actionNote')el.disabled=disabled})}
function button(label,action,cls='crew-button'){return `<button class="${cls}" type="button" data-review-action="${action}">${label}</button>`}
function renderActions(){const left=[],right=[];if(!current){right.push(button('Save Rough','import','crew-button primary'));}else{if(canEdit){right.push(button('Save Changes','save','crew-button'));if(current.status==='rough'&&can('reviews.finalize'))right.push(button('Mark Final','finalize','crew-button primary'));if(current.status==='final'&&can('reviews.edit_final'))left.push(button('Return to Rough','return'));if(current.status==='verified'&&can('reviews.edit_verified'))left.push(button('Revoke Verification','revoke_verification'));if(current.status==='published'&&can('reviews.unpublish'))left.push(button('Unpublish','unpublish'));if(current.status!=='trash')left.push(button('Move to Trash','trash','crew-button danger-button'));}if(current.status==='final'&&can('reviews.verify'))right.push(button('Verify','verify','crew-button primary'));if(current.status==='verified'&&can('reviews.publish'))right.push(button('Publish','publish','crew-button primary'));if(current.status==='trash'&&can('reviews.trash_restore'))right.push(button('Restore as Rough','restore','crew-button primary'));if(current.status==='trash'&&can('reviews.permanent_delete'))left.push(button('Permanent Delete','permanent_delete','crew-button danger-button'));}$('leftActions').innerHTML=left.join('');$('rightActions').innerHTML=right.join('')}
function needsNote(action){return['save_final','save_verified','save_published','return','verify','revoke_verification','unpublish','trash','restore','permanent_delete'].includes(action)}
function showNote(required){$('noteWrap').hidden=!required;if(required)$('actionNote').focus()}
async function loadAudit(reviewId){if(!can('reviews.view_audit')){$('auditSection').hidden=true;return}try{const d=await api(`/crew/reviews/audit?reviewId=${encodeURIComponent(reviewId)}`);$('auditSection').hidden=false;$('auditList').innerHTML=(d.events||[]).map(e=>`<div class="audit-event"><strong>${esc(String(e.action||'').replaceAll('_',' '))}</strong><small>${esc(e.actor_name||e.actor_email||'System')} · ${esc(fmt(e.performed_at))}${e.from_status||e.to_status?` · ${esc(e.from_status||'—')} → ${esc(e.to_status||'—')}`:''}</small>${e.note?`<p>${esc(e.note)}</p>`:''}</div>`).join('')||'<div class="review-empty">No audit events yet.</div>'}catch{$('auditSection').hidden=true}}
function populateForm(r){current=r||null;dialogMessage('');$('actionNote').value='';$('noteWrap').hidden=true;$('dialogEyebrow').textContent=r?'REVIEW RECORD':'IMPORT REVIEW';$('dialogTitle').textContent=r?r.reviewId:'Import Review';$('recordMeta').textContent=r?`${r.status.toUpperCase()} · Version ${r.recordVersion} · Imported ${fmt(r.importedAt)}`:'A legitimate external customer review will be saved as a private Rough.';$('source').value=r?.source||'';$('sourceUrl').value=r?.sourceUrl||'';$('reviewDate').value=r?.reviewDate||'';$('reviewerName').value=r?.reviewerName||'';$('rating').value=r?.rating||'';$('reviewText').value=r?.originalReviewText||'';$('reviewType').value=r?.reviewType||'business';$('featuredPriority').value=r?.featuredPriority||0;$('internalNotes').value=r?.internalNotes||'';document.querySelectorAll('#cookiePicker input').forEach(x=>x.checked=(r?.cookieIds||[]).includes(x.value));setFormDisabled(r?!canEdit:false);renderActions();if(r)loadAudit(r.reviewId);else $('auditSection').hidden=true;$('reviewDialog').showModal()}
async function openReview(id){try{const d=await api(`/crew/reviews/record?reviewId=${encodeURIComponent(id)}`);canEdit=d.canEdit===true;permissions=d.permissions||permissions;populateForm(d.review)}catch(e){message(e.message,'error')}}
async function perform(action){dialogMessage('');const note=$('actionNote').value.trim();const status=current?.status;if(action==='save'&&status!=='rough'&&!note){showNote(true);dialogMessage('A change note is required for edits after Rough.','error');return}if(needsNote(action)&&!note){showNote(true);dialogMessage('A note/reason is required for this action.','error');return}try{let d;if(action==='import'){const payload=formData();try{d=await api('/crew/reviews/import',{method:'POST',body:JSON.stringify(payload)})}catch(e){if(e.data?.code!=='POSSIBLE_DUPLICATE')throw e;const match=e.data?.warnings?.find(w=>w.code==='possible_duplicate');const existing=match?.reviewId||'an existing review';const proceed=confirm(`Possible duplicate detected: ${existing}.\n\nReview the existing record before continuing.\n\nChoose OK only if this is a separate legitimate review and you intentionally want to import it anyway.`);if(!proceed){dialogMessage(`Import stopped. Check ${existing} before continuing.`,'error');return}d=await api('/crew/reviews/import',{method:'POST',body:JSON.stringify({...payload,duplicateAcknowledged:true})})}}else if(action==='save')d=await api('/crew/reviews/save',{method:'POST',body:JSON.stringify(formData())});else if(action==='permanent_delete'){if(!confirm(`Permanently delete ${current.reviewId}? This cannot be restored from the Reviews Manager.`))return;d=await api('/crew/reviews/permanent-delete',{method:'POST',body:JSON.stringify({reviewId:current.reviewId,recordVersion:current.recordVersion,note})})}else{if(action==='trash'&&!confirm(`Move ${current.reviewId} to Trash? You may lose access to it after this action.`))return;d=await api('/crew/reviews/action',{method:'POST',body:JSON.stringify({reviewId:current.reviewId,recordVersion:current.recordVersion,action,note})})}dialogMessage(action==='import'?`${d.reviewId} imported as Rough.`:'Review updated.','success');await loadAll();if(action==='permanent_delete'){setTimeout(()=>$('reviewDialog').close(),350);return}if(d.reviewId){setTimeout(()=>openReview(d.reviewId),250)}}catch(e){if(e.data?.code==='STALE_REVIEW')dialogMessage('This review changed while you were working on it. Close and reopen the record to refresh it.','error');else dialogMessage(e.message,'error')}}
async function init(){session=await window.OBA_CREW_AUTH.requireCrewSession();if(!session)return;window.OBA_CREW_SHELL.mount({activePage:'reviews'});window.OBA_CREW_SHELL.renderCrewIdentity(session);permissions=session.user?.effectivePermissions||{};if(!can('reviews.view')){message('Your Crew account does not have access to Reviews.','error');$('importReview').hidden=true;return}const c=await api('/crew/reviews/cookies');cookies=c.cookies||[];$('cookiePicker').innerHTML=cookies.map(c=>`<label class="cookie-choice"><input type="checkbox" value="${esc(c.cookieId)}"><span>${esc(c.name)} <small>${esc(c.cookieId)}</small></span></label>`).join('');await loadAll()}
$('refreshReviews').addEventListener('click',loadAll);$('importReview').addEventListener('click',()=>{canEdit=true;populateForm(null)});$('closeDialog').addEventListener('click',()=>$('reviewDialog').close());$('reviewSearch').addEventListener('input',renderRows);$('sourceFilter').addEventListener('change',renderRows);$('statusFilter').addEventListener('change',()=>{trashMode=false;loadAll()});$('viewTrash').addEventListener('click',()=>{trashMode=true;loadAll()});$('reviewRows').addEventListener('click',e=>{const tr=e.target.closest('tr[data-review-id]');if(tr)openReview(tr.dataset.reviewId)});$('reviewType').addEventListener('change',()=>{if($('reviewType').value==='business')document.querySelectorAll('#cookiePicker input').forEach(x=>x.checked=false)});document.addEventListener('click',e=>{const b=e.target.closest('[data-review-action]');if(!b)return;const a=b.dataset.reviewAction;if(needsNote(a)&&$('noteWrap').hidden){showNote(true);return}perform(a)});document.addEventListener('DOMContentLoaded',init);
})();
